image: Visual Studio 2017

platform:
  - Any CPU

configuration:
  - Debug

before_build:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
#  - nuget restore

build_script:
  - build.bat
